### ISSUE TITLE
Wheelhouse does not generate settings.json files for apps

### ISSUE THREAD

**Issue by tyleha** [streamplace/wheelhouse#100]
Previously, `wheelhouse run stage -r` correctly ran `run/settings` on a per-app basis as it relied on the `startApp` bash function.

`wheelhouse start` or `wheelhouse start -a maestro` does not do any such thing.

**Comment by iameli** [comment]
Got it. I'm thinking probably we should just teach the apps to generate their own `settings.json` files upon boot, maybe a `beforeDev` hook in `package.json`... looking into it now.

**Comment by iameli** [comment]
Closed by #106, released in 0.2.3
