### ISSUE TITLE
wheelhouse browser focus on starts up

### ISSUE THREAD

**Issue by alex9311** [streamplace/wheelhouse#74]
would it possible not to have wheelhouse take your browser focus when it starts up? Or have a setting for that?

**Comment by meonkeys** [comment]
#77 is one idea, although see my description in that PR... I'd rather _not_ opening a new browser window/tab were the default.

**Comment by alex9311** [comment]
Your solution seems good to me! WHere do you set `openBrowserOnStartup`? Some yaml file somewhere?

**Comment by meonkeys** [comment]
Yep, `wheelhouse.yaml`. Also: I had the logic reversed in that MR, but I just fixed it.

**Comment by iameli** [comment]
Fixed by #77 

I'm gonna leave the default for now, but C-SATS should tweak their `wheelhouse.yaml` and y'all have the behavior you'd like.
