### ISSUE TITLE
Allow default-auto-start option to automatically start a set of apps with every wheelhouse start

### ISSUE THREAD

**Issue by chasemaier** [streamplace/wheelhouse#78]
Maybe something like `wheelhouse.yaml` becomes:

````
packages:
  - mendoza
  - maestro
  - wolfgang
  - clydesdale
  - telestration
  - tealtown
  - packages/*

autoStartPackages:
  - mendoza
  - maestro
  - wolfgang
  - clydesdale
  - tealtown

env:
  - ...
````

**Comment by iameli** [comment]
Yeah, that'll be in this ticket: https://github.com/streamplace/wheelhouse/issues/71

I think in general I want per-app settings to be within the `package.json` of individual apps instead of ending up with a really really big `wheelhouse.yaml` file.

**Comment by chasemaier** [comment]
Cool.
