### ISSUE TITLE
Really long non-breaking log lines blow out dashboard UI

### ISSUE THREAD

**Issue by chasemaier** [streamplace/wheelhouse#79]
One of the apps running outputted a log message containing some sort of token/generated string that resulted in a 953+ character log line without any naturally breakable characters.

This appears to have blown out the UI so large horizontal scroll bars exist on the page and the logs container -- even on a 21:9 monitor.

![image](https://cloud.githubusercontent.com/assets/2565985/26372982/b08e6768-3fb4-11e7-839d-34b5016cb8b4.png)

![image](https://cloud.githubusercontent.com/assets/2565985/26373015/d1bbbe18-3fb4-11e7-95d6-4b39ddc47fdb.png)

**Comment by iameli** [comment]
Wow! We once had wrapping log lines, looks like something must have made them stop working.

**Comment by iameli** [comment]
Fixed by #94
